# Generated by Django 4.1.2 on 2023-01-24 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100)),
                ("category_id", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Grocery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grocery_name", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="grocery_photos")),
            ],
            options={
                "verbose_name_plural": "groceries",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("product_link", models.URLField()),
                ("photo", models.ImageField(upload_to="product_photos")),
                ("is_vegan", models.BooleanField()),
                ("is_cooled", models.BooleanField()),
                ("is_local_product", models.BooleanField()),
                ("is_bio", models.BooleanField()),
                ("on_stock", models.CharField(max_length=50)),
                (
                    "categories",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="grocery.category",
                    ),
                ),
                (
                    "is_favorite_of",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="sold_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sold_by",
                to="grocery.grocery",
            ),
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=1, max_digits=9)),
                ("sale_value", models.DecimalField(decimal_places=1, max_digits=9)),
                ("unit", models.CharField(default="darab", max_length=20)),
                ("unit_price", models.DecimalField(decimal_places=1, max_digits=9)),
                ("timestamp", models.DateField(default=django.utils.timezone.now)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="grocery.item",
                    ),
                ),
            ],
            options={
                "unique_together": {("value", "timestamp", "item")},
            },
        ),
    ]
